# Generated by Django 5.1.1 on 2024-10-01 11:00

import django.core.validators
import re
import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=255)),
                ('street_address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state_province', models.CharField(max_length=100)),
                ('postal_zip_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('position_applied_for', models.CharField(max_length=255)),
                ('resume_cv', models.FileField(upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('cover_letter', models.TextField()),
                ('current_level_of_experience', models.CharField(choices=[('Entry Level', 'Entry Level(0-3)'), ('Mid Level', 'Mid Level(3-7)'), ('Senior Level', 'Senior Level(7-13)'), ('Other', 'Other')], max_length=20)),
                ('earliest_possible_start_date', models.DateField(null=True)),
                ('consent_to_privacy_policy', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z]+$'), 'Enter a valid username', 'invalid')])),
                ('password', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(re.compile('^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[!@#$%^&*()_+=-{};:"<>,./?]).{8,}$'), 'Password should be at least 8 characters, and contain at least one letter, one number, and one special character', 'invalid')])),
            ],
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='confirm_password',
            field=models.CharField(max_length=128, validators=[website.models.validate_password]),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='first_name',
            field=models.CharField(max_length=50, validators=[website.models.validate_name]),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='last_name',
            field=models.CharField(max_length=50, validators=[website.models.validate_name]),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='password',
            field=models.CharField(max_length=128, validators=[website.models.validate_password]),
        ),
    ]
