# Generated by Django 5.1.1 on 2024-10-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_user_username_user_email_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
